server:
  port: 8080

spring:
  application:
    name: gatewayservice
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
      routes:
        - id: authservice
          uri: lb://authservice
          predicates:
            - Path=/auth/**
        - id: anagservice
          uri: lb://anagservice
          predicates:
            - Path=/anag/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

