# for comments, check the anagraficaService application.yml

server:
  port: 8083

spring:
  application:
    name: notificationservice
  datasource:
    url: jdbc:mysql://localhost:3306/notification?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
  # Spring Cloud Stream RabbitMQ bindings
  cloud:
    stream:
      bindings:
        mailSender-in-0:
          destination: notifications
          binder: rabbitmq
      binders:
        rabbitmq:
          type: rabbit
          port: "5672"
          networks:
            - default
  # JPA settings
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  # File size limits
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  # Spring mail settings
  mail:
    host: ${mail.server.host}
    port: ${mail.server.port}
    username: ${mail.username}
    password: ${mail.server.token}
    properties:
      mail:
        smtp:
          auth: true
          quitwait: false
          starttls:
            required: true
            enable: true

# Eureka settings
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8772/eureka/
# App Properties
contrader:
  app:
    jwtCookieName: contrader
    jwtSecret: ascihabcoiacv987v89davahvbaiva98v9ava0svavibvais
    jwtExpirationMs: 86400000

